### ISSUE TITLE
synatx error json video not ge generated

### ISSUE THREAD

**Issue by todaysprint** [layerhub-io/layerhub-renderer#3]
SyntaxError: Unexpected token 'S', "Something went wrong" is not valid JSON

TypeError: Cannot read properties of undefined (reading 'map')
    at prepareDesign (file:///D:/canva/render/layerhub-renderer/src/prepare-design.ts:6:40)     
    at new VideoRenderer (file:///D:/canva/render/layerhub-renderer/src/video-renderer.ts:37:20)
    at file:///D:/canva/render/layerhub-renderer/src/index.ts:22:22
    at Layer.handle [as handle_request] (D:\canva\render\layerhub-renderer\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\canva\render\layerhub-renderer\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\canva\render\layerhub-renderer\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\canva\render\layerhub-renderer\node_modules\express\lib\router\layer.js:95:5)
    at D:\canva\render\layerhub-renderer\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\canva\render\layerhub-renderer\node_modules\express\lib\router\index.js:346:12)
    at next (D:\canva\render\layerhub-renderer\node_modules\express\lib\router\index.js:280:10)

**Comment by todaysprint** [comment]
fixed
